CREATE TABLE public.profiles (
  id             uuid PRIMARY KEY DEFAULT auth.uid(),
  participant_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  first_name     text NOT NULL,
  last_name      text NOT NULL,
  date_of_birth  date NOT NULL,
  biological_sex smallint NOT NULL,
  timezone       text,
  created_at     timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT profiles_participant_id_key UNIQUE (participant_id),
  CONSTRAINT profiles_id_fkey
    FOREIGN KEY (id)
    REFERENCES auth.users (id)
    ON DELETE CASCADE
);

CREATE TABLE public.studies (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        text NOT NULL,
  title       text NOT NULL,
  description text NOT NULL,
  status      text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT studies_slug_key UNIQUE (slug),
  CONSTRAINT studies_status_check
    CHECK (status = ANY (ARRAY['recruiting', 'recruiting paused', 'closed']))
);

CREATE TABLE public.consents (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid        NOT NULL    DEFAULT auth.uid(),
  study_id         uuid        NOT NULL,
  consent_version  text        NOT NULL,
  consent_pdf_path text        NOT NULL,
  signed_at        timestamptz NOT NULL    DEFAULT now(),

  CONSTRAINT consents_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES auth.users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT consents_study_id_fkey
    FOREIGN KEY (study_id)
    REFERENCES public.studies (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  -- a user should only be able to sign a given consent version once per study, adding a uniqueness constraint
  CONSTRAINT consents_user_study_version_key
    UNIQUE (user_id, study_id, consent_version)
);


CREATE TABLE public.audiograms (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid        NOT NULL    DEFAULT auth.uid(),
  created_at      timestamptz NOT NULL    DEFAULT now(),
  measured_at     timestamptz NOT NULL,
  source          text        NOT NULL,
  headphone_name  text        NOT NULL,
  frequency_data  jsonb       NOT NULL,

  CONSTRAINT audiograms_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES auth.users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE public.study_enrollments (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL,
  study_id    uuid NOT NULL,
  status      text NOT NULL
    CHECK (status IN ('enrolled', 'withdrawn', 'completed', 'screen_failed')),
  enrolled_at timestamptz NOT NULL DEFAULT now(),
  created_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT study_enrollments_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES auth.users (id)
    ON DELETE CASCADE,

  CONSTRAINT study_enrollments_study_id_fkey
    FOREIGN KEY (study_id)
    REFERENCES public.studies (id)
    ON DELETE CASCADE,

  CONSTRAINT study_enrollments_user_study_key
    UNIQUE (user_id, study_id)
);

CREATE TABLE public.scheduled_tasks (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  enrollment_id uuid NOT NULL
    REFERENCES public.study_enrollments (id) ON DELETE CASCADE,

  -- minimal "what task is this" identifier (keep task algos in code)
  task_key     text NOT NULL, -- e.g. 'lm_1khz_v1'
  task_version int  NOT NULL DEFAULT 1,

  -- schedule + gating window
  scheduled_for timestamptz NOT NULL,
  window_start  timestamptz NOT NULL,
  window_end    timestamptz NOT NULL,

  -- lifecycle
  status text NOT NULL DEFAULT 'scheduled'
    CHECK (status IN ('scheduled', 'completed', 'missed', 'skipped', 'cancelled')),

  -- helps deterministic ordering in UI/exports
  day_index  int NOT NULL, -- 0..6
  slot_index int NOT NULL, -- 0..3

  created_at   timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,

  CONSTRAINT scheduled_tasks_unique_slot
    UNIQUE (enrollment_id, day_index, slot_index)
);


CREATE TABLE public.task_runs (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scheduled_task_id uuid NOT NULL
    REFERENCES public.scheduled_tasks (id) ON DELETE CASCADE,
  enrollment_id     uuid NOT NULL
    REFERENCES public.study_enrollments (id) ON DELETE CASCADE,
  user_id           uuid NOT NULL DEFAULT auth.uid()
    REFERENCES auth.users (id) ON DELETE CASCADE,

  run_status text NOT NULL DEFAULT 'completed'
    CHECK (run_status IN ('completed', 'aborted', 'failed')),

  started_at   timestamptz,
  completed_at timestamptz,
  submitted_at timestamptz NOT NULL DEFAULT now(),

  -- reproducibility / audit
  app_version         text,          -- e.g. 1.2.0
  protocol_version    text NOT NULL,  -- e.g. 'lm_v1'
  calibration_version text,          -- e.g. 'retspl_rk_2025-01'
  device_info         jsonb,         -- model, iOS version
  headphone_info      jsonb,         -- route name, model id, firmware (if available)

  -- gating outputs (logic in code, results stored here)
  gating      jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- the raw task payload (all trials/slider moves/etc)
  raw_payload jsonb NOT NULL,

  created_at  timestamptz NOT NULL DEFAULT now()
);